import { type NextRequest, NextResponse } from "next/server"

export async function GET(request: NextRequest, { params }: { params: { id: string } }) {
  const lectureId = params.id

  // Mock summary data - in real app, this would be generated by AI
  const summaries: Record<string, any> = {
    "1": {
      chapters: [
        {
          title: "Introduction to AI",
          content:
            "Overview of artificial intelligence concepts, definitions, and the scope of modern AI applications.",
          timestamp: "00:00 - 02:00",
        },
        {
          title: "Types of AI",
          content: "Exploration of Narrow AI, General AI, and Superintelligence with focus on current applications.",
          timestamp: "02:15 - 08:30",
        },
        {
          title: "Machine Learning Basics",
          content: "Introduction to machine learning as a subset of AI and its learning mechanisms.",
          timestamp: "08:45 - 15:00",
        },
        {
          title: "Natural Language Processing",
          content: "Understanding NLP and its role in human-computer interaction through language.",
          timestamp: "15:00 - 22:00",
        },
      ],
    },
    "2": {
      chapters: [
        {
          title: "What is Machine Learning?",
          content: "Definition and core concepts of machine learning, including supervised and unsupervised learning.",
          timestamp: "00:00 - 03:00",
        },
        {
          title: "Types of Learning",
          content: "Deep dive into supervised, unsupervised, and reinforcement learning paradigms.",
          timestamp: "03:00 - 10:00",
        },
        {
          title: "Common Algorithms",
          content: "Overview of popular ML algorithms including decision trees, neural networks, and clustering.",
          timestamp: "10:00 - 18:00",
        },
        {
          title: "Real-world Applications",
          content: "Examples of machine learning in industry, healthcare, finance, and everyday technology.",
          timestamp: "18:00 - 25:00",
        },
      ],
    },
    "3": {
      chapters: [
        {
          title: "Neural Networks Fundamentals",
          content: "Basic structure and function of artificial neural networks and their biological inspiration.",
          timestamp: "00:00 - 05:00",
        },
        {
          title: "Deep Learning Architecture",
          content: "Understanding layers, weights, biases, and the forward propagation process.",
          timestamp: "05:00 - 12:00",
        },
        {
          title: "Training Deep Networks",
          content: "Backpropagation, gradient descent, and optimization techniques for deep learning.",
          timestamp: "12:00 - 20:00",
        },
        {
          title: "Applications and Future",
          content: "Current applications of deep learning and emerging trends in the field.",
          timestamp: "20:00 - 28:00",
        },
      ],
    },
  }

  const summary = summaries[lectureId] || {
    chapters: [
      {
        title: "Content Summary",
        content: "AI-generated summary will be available here once the lecture is processed.",
        timestamp: "00:00 - 00:00",
      },
    ],
  }

  return NextResponse.json({ summary })
}
